# Generated by Django 3.2.13 on 2022-05-27 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0002_auto_20220526_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('ludt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
